package com.minhacarteira.model.enums;

public enum Setor {
	PAPEL, LOGISTICA, LAJES, SHOPPINGS, HIBRIDOS, FUNDOS_DE_FUNDOS, BANCARIO, ENERGIA_ELETRICA, ENERGIA,
	TELECOMUNICACOES, VAREJO, TECNOLOGIA, SAUDE, CONSTRUCAO_ENGENHARIA, ALIMENTOS_BEBIDAS, MINERACAO_SIDERURGIA,
	EDUCACAO, PAPEL_CELULOSE, INDUSTRIA, PETROLEO, FINANCEIRO
}
